name: "Publish"

on:
    release:
        types: [published]

jobs:
    release:
        name: "Publish"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3.5.3
            - name: "Node"
              uses: actions/setup-node@v3.7.0
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org/
            - name: "Install"
              run: npm ci
            - name: "Lint"
              run: npm run lint
            - name: "Format"
              run: npm run format
            - name: "Test"
              run: npm run test
            - name: "Publish"
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
